spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: 1234
  jpa:
    hibernate:
        ddl-auto: update
    show-sql: true
server:
  port: 808011
  servlet:
    context-path: /identiy

